import { useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { FileText } from "lucide-react";
import ReactMarkdown from "react-markdown";

import readme from "@/examples/README.md?raw";
import api from "@/examples/API.md?raw";
import contributing from "@/examples/CONTRIBUTING.md?raw";

const docs = [
  { id: "readme", title: "README.md", content: readme },
  { id: "api", title: "API.md", content: api },
  { id: "contributing", title: "CONTRIBUTING.md", content: contributing },
];

export default function Examples() {
  const [active, setActive] = useState(docs[0]);

  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-orange-50 py-20">
      <div className="max-w-7xl mx-auto px-4">
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
            Example Documentation
          </h1>
          <p className="text-xl text-gray-600">
            Real output generated by GitCrafts from real repositories
          </p>
        </div>

        {/* Tabs */}
        <div className="flex flex-wrap justify-center gap-4 mb-10">
          {docs.map((doc) => (
            <Button
              key={doc.id}
              variant={active.id === doc.id ? "default" : "outline"}
              className={
                active.id === doc.id
                  ? "bg-orange-600 hover:bg-orange-700"
                  : "border-orange-600 text-orange-600 hover:bg-orange-50"
              }
              onClick={() => setActive(doc)}
            >
              <FileText className="mr-2 h-4 w-4" />
              {doc.title}
            </Button>
          ))}
        </div>

        {/* Markdown preview */}
        <Card className="border-2">
          <CardContent className="p-8 prose max-w-none prose-orange">
            <ReactMarkdown>{active.content}</ReactMarkdown>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
