import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import {
  FileText,
  Zap,
  Shield,
  Github,
  ArrowRight,
  Eye,
} from "lucide-react";

export default function Landing() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-orange-50">
      {/* Navigation */}
      <nav className="border-b bg-white/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 py-4 flex justify-between items-center">
          <div className="flex items-center gap-2">
            <span className="text-2xl font-bold text-gray-900">GitCrafts</span>
          </div>
          <div className="hidden md:flex items-center gap-8">
            <a href="/features" className="text-gray-600 hover:text-orange-600 transition">
              Features
            </a>
            <a href="/pricing" className="text-gray-600 hover:text-orange-600 transition">
              Pricing
            </a>
            <a href="/how-it-works" className="text-gray-600 hover:text-orange-600 transition">
              How it Works
            </a>
          </div>
          <Button
            onClick={() => navigate("/login")}
            className="bg-orange-600 hover:bg-orange-700"
          >
            Get Started
          </Button>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="max-w-7xl mx-auto px-4 py-20 md:py-32">
        <div className="text-center max-w-4xl mx-auto">
          <div className="inline-flex items-center gap-2 bg-orange-100 text-orange-600 px-4 py-2 rounded-full mb-8">
            <Zap className="h-4 w-4" />
            <span className="text-sm font-medium">AI-powered documentation</span>
          </div>

          <h1 className="text-5xl md:text-7xl font-bold text-gray-900 mb-6">
            AI-powered builder
            <br />
            <span className="text-orange-600">for your projects</span>
          </h1>

          <p className="text-xl md:text-2xl text-gray-600 mb-12 max-w-3xl mx-auto">
            GitCrafts lets you generate professional documentation in minutes for your projects
            using AI, no coding required. Built for developers, by developers
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center mb-16">
            <Button
              size="lg"
              onClick={() => navigate("/login")}
              className="bg-orange-600 hover:bg-orange-700 text-white px-8 py-6 text-lg"
            >
              <Github className="mr-2 h-5 w-5" />
              Start Building Free
            </Button>
            <Button
              size="lg"
              variant="outline"
              onClick={() => navigate("/pricing")}
              className="border-2 border-gray-900 text-gray-900 hover:bg-gray-50 px-8 py-6 text-lg"
            >
              View Pricing
              <ArrowRight className="ml-2 h-5 w-5" />
            </Button>
          </div>

          {/* Supported documents */}
          <div className="bg-white rounded-2xl shadow-lg p-8 max-w-2xl mx-auto">
            <p className="text-gray-600 mb-4">Documents supported include</p>
            <div className="grid grid-cols-2 gap-3">
              <div className="flex items-center gap-2 px-4 py-3 bg-orange-50 rounded-lg">
                <FileText className="h-5 w-5 text-orange-600" />
                <span className="text-sm font-medium">README.md</span>
              </div>
              <div className="flex items-center gap-2 px-4 py-3 bg-orange-50 rounded-lg">
                <FileText className="h-5 w-5 text-orange-600" />
                <span className="text-sm font-medium">API Docs</span>
              </div>
              <div className="flex items-center gap-2 px-4 py-3 bg-orange-50 rounded-lg">
                <FileText className="h-5 w-5 text-orange-600" />
                <span className="text-sm font-medium">Contributing Guide</span>
              </div>
            </div>
          </div>

          {/* Examples teaser */}
          <div className="mt-16 max-w-4xl mx-auto">
            <Card className="border-2 border-dashed hover:border-orange-300 transition">
              <CardContent className="p-8 text-center">
                <div className="flex justify-center mb-4">
                  <div className="bg-orange-100 p-3 rounded-xl">
                    <Eye className="h-6 w-6 text-orange-600" />
                  </div>
                </div>

                <h3 className="text-2xl font-bold text-gray-900 mb-3">
                  See real docs generated by GitCrafts
                </h3>

                <p className="text-gray-600 mb-6 max-w-2xl mx-auto">
                  Preview actual README, API, and contributing docs generated from
                  real repositories — no mockups.
                </p>

                <div className="flex flex-col sm:flex-row gap-4 justify-center">
                  <Button
                    variant="outline"
                    className="border-orange-600 text-orange-600 hover:bg-orange-50"
                    onClick={() => navigate("/examples")}
                  >
                    View Examples
                    <ArrowRight className="ml-2 h-4 w-4" />
                  </Button>

                  <Button
                    className="bg-orange-600 hover:bg-orange-700"
                    onClick={() => navigate("/login")}
                  >
                    Generate Yours
                  </Button>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="bg-white py-20">
        <div className="max-w-7xl mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
              Why GitCrafts?
            </h2>
            <p className="text-xl text-gray-600">
              Professional documentation in seconds, powered by AI
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            <Card className="border-2">
              <CardContent className="p-8">
                <Zap className="h-7 w-7 text-orange-600 mb-6" />
                <h3 className="text-2xl font-bold mb-4">Lightning Fast</h3>
                <p className="text-gray-600">
                  Generate comprehensive documentation in under 60 seconds.
                </p>
              </CardContent>
            </Card>

            <Card className="border-2">
              <CardContent className="p-8">
                <Shield className="h-7 w-7 text-orange-600 mb-6" />
                <h3 className="text-2xl font-bold mb-4">Private & Secure</h3>
                <p className="text-gray-600">
                  Works with private repositories. We analyze structure only.
                </p>
              </CardContent>
            </Card>

            <Card className="border-2">
              <CardContent className="p-8">
                <FileText className="h-7 w-7 text-orange-600 mb-6" />
                <h3 className="text-2xl font-bold mb-4">Multiple Formats</h3>
                <p className="text-gray-600">
                  README, API docs, changelogs, and contributing guides.
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 text-center">
        <h2 className="text-4xl md:text-5xl font-bold mb-6">
          Ready to Get Started?
        </h2>
        <Button
          size="lg"
          onClick={() => navigate("/login")}
          className="bg-orange-600 hover:bg-orange-700 px-8 py-6 text-lg"
        >
          Start Free Today
          <ArrowRight className="ml-2 h-5 w-5" />
        </Button>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-12 text-center">
        <p className="text-gray-400 text-sm">
          © 2026 GitCrafts. All rights reserved.
        </p>
      </footer>
    </div>
  );
}
